Repository pybotters/pybotters, pull requests merged in 2021-08, with the labels that each got.

#78 Sphinxのドキュメントを追加
  docs/Advanced-Usage.rst
  docs/Contributing.rst
  docs/Example.rst
  docs/Exchanges.rst
  docs/Home.rst
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
Labels: documentation

#80 ✨v0.6.0リリース
  README.md
  docs/Advanced-Usage.rst
  docs/Contributing.rst
  docs/Example.rst
  docs/Exchanges.rst
  docs/Home.rst
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  poetry.lock
  pybotters/__init__.py
  pybotters/auth.py
  pybotters/models/binance.py
  pybotters/models/bitbank.py
  pybotters/models/bitmex.py
  pybotters/models/bybit.py
  pybotters/models/ftx.py
  pybotters/models/gmocoin.py
  pybotters/store.py
  pyproject.toml
  tests/test_auth.py
  tests/test_store.py
Labels: documentation, enhancement

#81 BybitのKlineのinitializeを追加する
  pybotters/models/bybit.py
Labels: enhancement
