Repository pybotters/pybotters, pull requests merged in 2022-03, with the labels that each got.

#137 bitbankDataStoreのDepthにtimestampを追加
  pybotters/models/bitbank.py
Labels: enhancement

#140 ✨v0.11.0リリース
  README.md
  poetry.lock
  pybotters/__init__.py
  pybotters/auth.py
  pybotters/client.py
  pybotters/models/binance.py
  pybotters/models/bitbank.py
  pybotters/models/bitget.py
  pybotters/models/bybit.py
  pybotters/models/coincheck.py
  pybotters/models/deprecated/bybit.py
  pybotters/models/experimental/__init__.py
  pybotters/models/experimental/bybit.py
  pybotters/models/gmocoin.py
  pybotters/models/okx.py
  pybotters/request.py
  pybotters/ws.py
  pyproject.toml
  tests/test_auth.py
  tests/test_client.py
  tests/test_request.py
  tests/test_ws.py
Labels: bug, enhancement

#141 🐛v0.11.1リリース[Hotfix]
  pybotters/ws.py
  pyproject.toml
Labels: bug

#152 ✨v0.12.0リリース
  README.md
  docs/conf.py
  pybotters/__init__.py
  pybotters/auth.py
  pybotters/client.py
  pybotters/models/binance.py
  pybotters/models/bitbank.py
  pybotters/models/bitflyer.py
  pybotters/models/bitget.py
  pybotters/models/bitmex.py
  pybotters/models/bybit.py
  pybotters/models/deprecated/bybit.py
  pybotters/models/ftx.py
  pybotters/models/gmocoin.py
  pybotters/models/phemex.py
  pybotters/request.py
  pybotters/store.py
  pybotters/ws.py
  pyproject.toml
  tests/test_auth.py
  tests/test_client.py
  tests/test_request.py
  tests/test_store.py
  tests/test_ws.py
Labels: enhancement
